[tool.poetry]
name = "olas-operate-app"
version = "0.2.0-rc225"
description = ""
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>"]
readme = "README.md"
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-middleware.git", rev = "7d791e5c3bfe2aae243fb7c780e3ce1441aa6867"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
