[tool.poetry]
name = "olas-operate-app"
version = "0.2.0-rc147"
description = ""
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>"]
readme = "README.md"
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-middleware.git", rev = "9eb48c15486a3e4b20a97c3c3437a6aedb828a7d"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
