[tool.poetry]
name = "olas-operate-app"
version = "0.2.0-rc242"
description = ""
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>"]
readme = "README.md"
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-middleware.git", rev = "a39666c0381cb3cc184bf14bb3ef87f4ae30c9f0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
